# Model configuration and cost table

default:
  name: "openai:gpt-4o-mini"
  temperature: 0.0
  max_tokens: 512

models:
  - name: "openai:gpt-4o-mini"
    cost:
      input_per_1k: 0.00015  # $0.15 per 1M tokens
      output_per_1k: 0.0006   # $0.60 per 1M tokens
  
  - name: "openai:gpt-4o"
    cost:
      input_per_1k: 0.0025   # $2.50 per 1M tokens
      output_per_1k: 0.01     # $10.00 per 1M tokens
  
  - name: "openai:gpt-4-turbo"
    cost:
      input_per_1k: 0.01      # $10 per 1M tokens
      output_per_1k: 0.03     # $30 per 1M tokens